version: '3'

volumes:
    db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/test-product'
    environment: 
      - 'DATABASE_PASSWORD=mysql'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb
    volumes:
      - 'db-data:/var/lib/mysql/data'
    environment: 
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: mysql